import os
import sys
import time
import tempfile
import shutil
import unittest
import re
import ast
from typing import List, Dict, Optional

# Insert the parent directory into python path to allow imports from backend
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from backend.api import API, ConversionCategory
import backend.config


class MockWindow:
    """
    Mock window class to capture evaluate_js calls and record events.
    """
    def __init__(self):
        self.events = []

    def evaluate_js(self, js_code: str) -> None:
        """
        Parses custom webview events dispatched by the backend.
        
        Args:
            js_code (str): The raw JavaScript code dispatched to webview.
        """
        # Match event name and details dict using regex
        match = re.search(r"CustomEvent\('([^']+)',\s*\{detail:\s*(.+)\}\)\);", js_code)
        if match:
            event_name = match.group(1)
            data_str = match.group(2)
            try:
                # Safely evaluate Python dict representation generated by f-string data serialization
                data = ast.literal_eval(data_str)
                self.events.append((event_name, data))
            except Exception:
                self.events.append((event_name, data_str))


class TestAPI(unittest.TestCase):
    """
    Test suite for testing the full API functionality.
    """
    @classmethod
    def setUpClass(cls):
        # Paths to test files
        cls.test_files_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'test_files'))
        cls.jpg_path = os.path.join(cls.test_files_dir, 'anime-girl-white-short-hair.jpg')
        cls.mp4_path = os.path.join(cls.test_files_dir, 'clip_1.mp4')
        cls.otf_path = os.path.join(cls.test_files_dir, 'DepartureMonoNerdFontMono-Regular.otf')
        cls.md_path = os.path.join(cls.test_files_dir, 'propuesta.md')

        # Verify test files exist
        for path in [cls.jpg_path, cls.mp4_path, cls.otf_path, cls.md_path]:
            if not os.path.isfile(path):
                raise FileNotFoundError(f"Required test file not found: {path}")

    def _wait_for_conversion(self, window: MockWindow, timeout: float = 30.0) -> None:
        """
        Helper method to wait for async batch conversions to finish.
        
        Args:
            window (MockWindow): The mocked window object recording events.
            timeout (float): Max wait time in seconds.
        """
        start_time = time.time()
        while time.time() - start_time < timeout:
            # Check if queue execution is completed
            if any(e[0] == "batch_complete" for e in window.events):
                return
            
            # Fail immediately if any processing errors are reported
            err_events = [e for e in window.events if e[0] in ("batch_file_error", "batch_error")]
            if err_events:
                self.fail(f"Conversion queue failed with event: {err_events[0]}")
                
            time.sleep(0.1)
        self.fail("Conversion task timed out")

    def test_get_supported_formats(self) -> None:
        """
        Tests that get_supported_formats returns valid format lists for each category.
        """
        api = API()
        formats = api.get_supported_formats()
        
        self.assertIsInstance(formats, dict)
        for category in ConversionCategory:
            self.assertIn(category.value, formats)
            self.assertIsInstance(formats[category.value], list)
            self.assertTrue(len(formats[category.value]) > 0)
            self.assertTrue(all(isinstance(f, str) for f in formats[category.value]))

    def test_config_management(self) -> None:
        """
        Tests configuration exists, read, and write operations using a mock file path.
        """
        # Create a temporary config file path
        fd, temp_config_path = tempfile.mkstemp(suffix=".json", prefix="test_config_")
        os.close(fd)
        
        # Override the get_config_path function pointer
        original_get_config_path = backend.config._get_config_path_fn
        backend.config._get_config_path_fn = lambda: temp_config_path
        
        try:
            # Delete temporary file to test initial state where file is missing
            if os.path.exists(temp_config_path):
                os.remove(temp_config_path)

            api = API()
            
            # 1. Test config_exists initially false
            self.assertFalse(api.config_exists())

            # 2. Test read_config auto-creates config with defaults
            config = api.read_config()
            self.assertEqual(config, {"lang": "es", "theme": "dracula"})
            self.assertTrue(api.config_exists())

            # 3. Test update_config updates preferences
            api.update_config(lang="en", theme="nord")
            updated_config = api.read_config()
            self.assertEqual(updated_config, {"lang": "en", "theme": "nord"})
            
        finally:
            # Cleanup config override and temporary file
            backend.config._get_config_path_fn = original_get_config_path
            if os.path.exists(temp_config_path):
                os.remove(temp_config_path)

    def test_binary_diagnostics(self) -> None:
        """
        Tests checking binary status and fetching correct tool paths.
        """
        api = API()
        status = api.check_binaries()
        paths = api.get_binary_paths()

        self.assertIsInstance(status, dict)
        self.assertIn("ffmpeg", status)
        self.assertIn("webp", status)
        self.assertIn("pandoc", status)

        self.assertIsInstance(paths, dict)
        self.assertIn("ffmpeg", paths)
        self.assertIn("webp", paths)
        self.assertIn("pandoc", paths)

    def test_download_binaries_completed(self) -> None:
        """
        Tests the asynchronous downloader starts and reports status correctly.
        """
        api = API()
        window = MockWindow()
        api.set_window(window)

        res = api.download_binaries()
        self.assertEqual(res, {"status": "download_started"})

        # Wait for download thread to terminate
        timeout = 5.0
        start_time = time.time()
        while time.time() - start_time < timeout:
            if any(e[0] == "download_complete" for e in window.events):
                break
            time.sleep(0.1)

        complete_events = [e for e in window.events if e[0] == "download_complete"]
        self.assertTrue(len(complete_events) > 0)
        # Verify it completes without crashing
        self.assertIn(complete_events[0][1]["status"], ["all_installed", "success"])

    def test_convert_audio(self) -> None:
        """
        Tests converting video to audio using the audio pipeline.
        """
        temp_dir = tempfile.mkdtemp()
        try:
            api = API()
            window = MockWindow()
            api.set_window(window)

            api.process_batch(
                file_paths=[self.mp4_path],
                save_path=temp_dir,
                target_format="mp3",
                category="audio"
            )

            self._wait_for_conversion(window)
            
            output_file = os.path.join(temp_dir, "clip_1.mp3")
            self.assertTrue(os.path.isfile(output_file))
            self.assertTrue(os.path.getsize(output_file) > 0)
        finally:
            shutil.rmtree(temp_dir)

    def test_convert_video(self) -> None:
        """
        Tests converting video using the video pipeline.
        """
        temp_dir = tempfile.mkdtemp()
        try:
            api = API()
            window = MockWindow()
            api.set_window(window)

            api.process_batch(
                file_paths=[self.mp4_path],
                save_path=temp_dir,
                target_format="avi",
                category="video"
            )

            self._wait_for_conversion(window)
            
            output_file = os.path.join(temp_dir, "clip_1.avi")
            self.assertTrue(os.path.isfile(output_file))
            self.assertTrue(os.path.getsize(output_file) > 0)
        finally:
            shutil.rmtree(temp_dir)

    def test_convert_document(self) -> None:
        """
        Tests converting markdown document using the pandoc document pipeline.
        """
        temp_dir = tempfile.mkdtemp()
        try:
            api = API()
            window = MockWindow()
            api.set_window(window)

            api.process_batch(
                file_paths=[self.md_path],
                save_path=temp_dir,
                target_format="html",
                category="document"
            )

            self._wait_for_conversion(window)
            
            output_file = os.path.join(temp_dir, "propuesta.html")
            self.assertTrue(os.path.isfile(output_file))
            self.assertTrue(os.path.getsize(output_file) > 0)
        finally:
            shutil.rmtree(temp_dir)

    def test_convert_image(self) -> None:
        """
        Tests converting image using the image pipeline (Pillow).
        """
        temp_dir = tempfile.mkdtemp()
        try:
            api = API()
            window = MockWindow()
            api.set_window(window)

            api.process_batch(
                file_paths=[self.jpg_path],
                save_path=temp_dir,
                target_format="png",
                category="image"
            )

            self._wait_for_conversion(window)
            
            output_file = os.path.join(temp_dir, "anime-girl-white-short-hair.png")
            self.assertTrue(os.path.isfile(output_file))
            self.assertTrue(os.path.getsize(output_file) > 0)
        finally:
            shutil.rmtree(temp_dir)

    def test_convert_font(self) -> None:
        """
        Tests converting OTF font using the fontTools font pipeline.
        """
        temp_dir = tempfile.mkdtemp()
        try:
            api = API()
            window = MockWindow()
            api.set_window(window)

            api.process_batch(
                file_paths=[self.otf_path],
                save_path=temp_dir,
                target_format="woff2",
                category="font"
            )

            self._wait_for_conversion(window)
            
            output_file = os.path.join(temp_dir, "DepartureMonoNerdFontMono-Regular.woff2")
            self.assertTrue(os.path.isfile(output_file))
            self.assertTrue(os.path.getsize(output_file) > 0)
        finally:
            shutil.rmtree(temp_dir)


if __name__ == '__main__':
    unittest.main()
